import{a as v,S,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&g(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function g(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const C="https://pixabay.com/api/",q="54003788-96a27274a1926d2f6361511ae";async function h(r,e=1){try{return(await v.get(C,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(o){throw new Error("Pixabay API error: "+o.message)}}const p=document.querySelector(".gallery"),l=document.querySelector(".loader"),B=new S(".gallery a");function y(r){const e=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",e),B.refresh()}function P(){p.innerHTML=""}function b(){l.classList.add("visible"),l.setAttribute("aria-hidden","false")}function c(){l.classList.remove("visible"),l.setAttribute("aria-hidden","true")}const w=document.querySelector(".load-more");function d(){w.style.display="block"}function L(){w.style.display="none"}const I=document.querySelector(".form"),$=document.querySelector(".load-more");let n="",f=1,m=0,i=0;I.addEventListener("submit",async r=>{if(r.preventDefault(),n=r.target.elements["search-text"].value.trim(),!n){a.warning({title:"Warning",message:"Please enter a search term!"});return}P(),f=1,i=0,L(),b();try{const e=await h(n,f);if(c(),e.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f44336",titleColor:"#ffffff",messageColor:"#ffffff",timeout:5e3,progressBar:!1,close:!1,class:"custom-error-toast"});return}y(e.hits),m=e.totalHits,i+=e.hits.length,i<m?d():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4e75ff",titleColor:"#ffffff",messageColor:"#ffffff",timeout:4e3,progressBar:!0})}catch(e){c(),a.error({title:"Error",message:"Something went wrong: "+e.message})}});$.addEventListener("click",async()=>{f+=1,b(),L();try{const r=await h(n,f);if(r.hits.length>0){y(r.hits),i+=r.hits.length;const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}c(),i<m?d():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4e75ff",titleColor:"#ffffff",messageColor:"#ffffff",timeout:4e3,progressBar:!0})}catch(r){c(),d(),a.error({title:"Error",message:"Something went wrong: "+r.message})}});
//# sourceMappingURL=index.js.map
