import{a as L,S as v,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&m(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function m(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",S="54003788-96a27274a1926d2f6361511ae";async function g(o,e=1){try{return(await L.get(q,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(r){throw new Error("Pixabay API error: "+r.message)}}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),I=new v(".gallery a");function p(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",e),I.refresh()}function A(){h.innerHTML=""}function y(){l.classList.add("visible"),l.setAttribute("aria-hidden","false")}function c(){l.classList.remove("visible"),l.setAttribute("aria-hidden","true")}const b=document.querySelector(".load-more");function P(){b.style.display="block"}function w(){b.style.display="none"}const $=document.querySelector(".form"),B=document.querySelector(".load-more");let i="",f=1,d=0,n=0;$.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){a.warning({title:"Warning",message:"Please enter a search term!"});return}A(),f=1,n=0,w(),y();try{const e=await g(i,f);if(p(e.hits),requestAnimationFrame(()=>{c()}),e.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f44336",titleColor:"#ffffff",messageColor:"#ffffff",timeout:5e3,progressBar:!1,close:!1,class:"custom-error-toast"});return}d=e.totalHits,n+=e.hits.length,n<d&&P()}catch(e){c(),a.error({title:"Error",message:"Something went wrong: "+e.message})}});B.addEventListener("click",async()=>{f+=1,y();try{const o=await g(i,f);p(o.hits),requestAnimationFrame(()=>{c()}),n+=o.hits.length;const e=document.querySelectorAll(".gallery-item");e[e.length-1].scrollIntoView({behavior:"smooth",block:"end"}),n>=d&&(w(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4e75ff",titleColor:"#ffffff",messageColor:"#ffffff",timeout:4e3,progressBar:!0}))}catch(o){c(),a.error({title:"Error",message:"Something went wrong: "+o.message})}});
//# sourceMappingURL=index.js.map
